### ISSUE TITLE
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/ruobr_vkbot#2]
Once the bot notified me twice about a new mark:
![image](https://user-images.githubusercontent.com/64320078/101632079-f1e7d400-3a57-11eb-9b73-d59eae4b4f35.png)

I checked the log and found that the problem is with PostgreSQL:
<details>

```
2020-12-09T08:24:37.738959+00:00 app[worker.1]: ERROR:root:
2020-12-09T08:24:37.738971+00:00 app[worker.1]: Traceback (most recent call last):
2020-12-09T08:24:37.738971+00:00 app[worker.1]: File "/app/notifier.py", line 26, in _loop
2020-12-09T08:24:37.738971+00:00 app[worker.1]: marks = await asyncio.gather(*tasks)
2020-12-09T08:24:37.738972+00:00 app[worker.1]: File "/app/notifier.py", line 60, in check_user
2020-12-09T08:24:37.738973+00:00 app[worker.1]: await self.db.update_marks(user.vk_id, json.dumps(new_marks))
2020-12-09T08:24:37.738973+00:00 app[worker.1]: File "/app/db_access.py", line 71, in update_marks
2020-12-09T08:24:37.738974+00:00 app[worker.1]: await self.conn.execute(
2020-12-09T08:24:37.738974+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/asyncpg/connection.py", line 297, in execute
2020-12-09T08:24:37.738975+00:00 app[worker.1]: _, status, _ = await self._execute(query, args, 0, timeout, True)
2020-12-09T08:24:37.738975+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/asyncpg/connection.py", line 1444, in _execute
2020-12-09T08:24:37.738976+00:00 app[worker.1]: with self._stmt_exclusive_section:
2020-12-09T08:24:37.738976+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/asyncpg/connection.py", line 1890, in __enter__
2020-12-09T08:24:37.738976+00:00 app[worker.1]: raise exceptions.InterfaceError(
2020-12-09T08:24:37.738976+00:00 app[worker.1]: asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
```
</details>

Even if the problem appears rarely, I need to fix it. I have to find a way to handle multiple operations at the same time. Of course, I can just wait for the connection to be released, but there's probably a better way.

**Comment by raitonoberu** [comment]
It was a mistake to store the connection in `self.conn` like that:
https://github.com/raitonoberu/ruobr_vkbot/blob/05e1111c0afb92570927d0f709a531daf166dbd7/db_access.py#L31-L41
The correct way is to use a connection pool that creates multiple connections:
https://github.com/raitonoberu/ruobr_vkbot/blob/ca2f08d418a643431fc7252af0c6382eb830fd44/db_access.py#L29-L40
More here: https://magicstack.github.io/asyncpg/current/usage.html#connection-pools
